import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { AppSidebar } from "@/components/AppSidebar";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Phần mềm chỉnh lý hồ sơ",
  description: "Generated by Gemini CLI",
};

import { getSession } from "@/lib/actions/auth";
import type { User } from "@/lib/types/user";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = (await getSession()) as User | null;

  return (
    <html lang="vi">
      <body className="h-screen flex flex-col overflow-hidden bg-background text-foreground antialiased">
        <SidebarProvider
          style={
            {
              "--sidebar-width": "calc(var(--spacing) * 72)",
              "--header-height": "calc(var(--spacing) * 12)",
            } as React.CSSProperties
          }
        >
          <AppSidebar user={session ?? undefined} />
          <SidebarInset>
            <Header user={session ?? undefined} />
            <div className="flex flex-1 flex-col">
              <div className="@container/main flex flex-1 flex-col gap-2 px-4 lg:px-6 py-4 md:py-6">
                {children}
              </div>
            </div>
          </SidebarInset>
        </SidebarProvider>
        <Toaster />
      </body>
    </html>
  );
}
