import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { AppSidebar } from "@/components/AppSidebar";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/sonner";

import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Phần mềm chỉnh lý hồ sơ",
  description: "Generated by Gemini CLI",
};

import { getSession } from "@/lib/actions/auth";
import type { User } from "@/lib/types/user";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = (await getSession()) as User | null;

  return (
    <html lang="vi" className={inter.variable}>
      <body className="h-screen flex flex-col overflow-hidden bg-background text-foreground antialiased">
        <SidebarProvider
          style={
            {
              "--sidebar-width": "calc(var(--spacing) * 72)",
              "--header-height": "calc(var(--spacing) * 12)",
            } as React.CSSProperties
          }
        >
          <AppSidebar user={session ?? undefined} />
          <SidebarInset>
            <Header user={session ?? undefined} />
            <div className="w-full flex flex-1 flex-col gap-2 p-4 lg:p-8 md:p-6 min-h-0 overflow-auto max-w-360 mx-auto">
              {children}
            </div>
          </SidebarInset>
        </SidebarProvider>
        <Toaster />
      </body>
    </html>
  );
}
